POST http://localhost:3003/signup
Content-Type: application/json

{
   	"name": "",
	"email": "",
	"password": ""
}

###

# @name login

POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "",
	"password": ""
}

### 

@token = {{login.response.body.token}}

###

POST http://localhost:3003/post
Content-Type: application/json
Authorization: {{token}}

{
   	"photo": "",
	"description": "",
	"type": ""
}

###
GET http://localhost:3003/post/
Authorization: {{token}}