POST http://localhost:3003/user
Content-Type: application/json

{
"id": "03",
"name": "Brisa",
"email": "brisa@email.com",
"password": "brisasenha"
}

###

GET http://localhost:3003/user

###

POST http://localhost:3003/products
Content-Type: application/json

{
"id": "03",
"name": "Coliseu",
"price": 130,
"image_url": "https://www.melhoresdestinos.com.br/wp-content/uploads/2017/09/roma-italia_1067-820x547.jpg"
}

###

GET http://localhost:3003/products

###


POST http://localhost:3003/purchases
Content-Type: application/json

{
"id": "03=",
"name": "Coliseu",
"price": 130,
"image_url": "https://www.melhoresdestinos.com.br/wp-content/uploads/2017/09/roma-italia_1067-820x547.jpg"
}
